\context ChordNames \chords {
	% intro
	\skip 4
	\skip 1*4
	\skip 1*4

	% Oh, Dios...
	\break
	\skip 1*4
	\break
	\skip 1*4

	% Mira este siervo tuyo...
	\break
	\skip 1*4
	\break
	\skip 1*4

	% Fortaleceme estas manos caidas...
	\break
	\skip 1*4
	\break
	\skip 1*4

	% Confiare en Yahve...
	\break
	\skip 1*4
	\break
	\skip 1*4
	%\skip 1*2

	% El mi roca a quien he de temer.
	\break
	%\skip 1*2
}
